routes/user/routes.py
import secrets
import sys
from uuid import uuid1

import bcrypt
from flask import Blueprint, render_template, request, jsonify, session

from routes.common.util import remember_me, cart_session, login_required, insert_address, insert_useraddress, \
    get_address_id, insert_userpayment, get_user_id, get_payment_id, \
    insert_payment, get_book_orderdetails, get_first_name, generate_secure_token
from routes.user.util import *
from server import mysql, fernet

user_bp = Blueprint('user_bp', __name__,
                    template_folder='templates', static_folder='static')


def get_books(cursor):
    if len(session['shopping_cart']) == 0:
        return redirect(url_for('common_bp.landing_page'))

    total_quantity = 0
    sub_total = 0
    # BOOKS FROM SHOPPING CART
    book_payload = {}
    for isbn, quantity in session['shopping_cart'].items():
        query = """SELECT nile_cover_ID, title, CONCAT(authorFirstName, ' ', authorLastName) AS author_name, 
        price FROM book WHERE ISBN = %s """
        cursor.execute(query, isbn)
        results = cursor.fetchall()[0]
        nile_cover_ID = results[0]
        title = results[1]
        author_name = results[2]
        price = results[3]
        total_price = price * quantity
        sub_total += total_price
        total_quantity += quantity
        book_payload[isbn] = {'nile_cover_id': nile_cover_ID, 'title': title,
                              'author_name': author_name, 'price': price, 'total_price': total_price,
                              'quantity': quantity}

    return {"book_payload": book_payload,
            "sub_total": sub_total,
            "book_quantity": total_quantity}


@user_bp.route('/checkout/shipping/', methods=['POST', 'GET'])
@login_required(session)
@secure_checkout(session)
@cart_session(session)
@remember_me(session)
@user_only(session)
def shipping_checkout():
    if len(session['shopping_cart']) == 0:
        return redirect(url_for('common_bp.landing_page'))

    conn = mysql.connect()
    cursor = conn.cursor()

    if request.method == 'GET':
        # SHIPPING ADDRESSES FROM DB
        shipping_payload = {}
        shipping_query = """
        SELECT * FROM address JOIN user_address ON  user_address.addressID_ua_FK = address.id 
        WHERE addressTypeID_address_FK=1 
        AND user_address.userID_ua_FK= (SELECT id FROM user WHERE email = %s)
        """
        cursor.execute(shipping_query, (session['email']))
        results = cursor.fetchall()
        for shipping_addr in results:
            shipping_payload[shipping_addr[0]] = {
                'street1': shipping_addr[1],
                'street2': shipping_addr[2],
                'city': shipping_addr[3],
                'zip': shipping_addr[4],
                'state': shipping_addr[5],
                'country': shipping_addr[6]
            }

        x = get_books(cursor)
        shipping_price = calculate_shipping(x['book_quantity'])

        conn.close()
        return render_template('checkout/shippingCheckout.html',
                               shipping_payload=shipping_payload,
                               book_payload=x['book_payload'],
                               sub_total=x['sub_total'],
                               shipping_price=shipping_price)
    elif request.method == 'POST':
        SHIPPING_IDENT = request.form.get('SHIPPING_IDENT')
        REMEMBER_SHIPPING = request.form.get('REMEMBER_SHIPPING')

        # USER CHOOSES NEW SHIPPING
        SHIPPING_HEADERS = ['street1', 'street2',
                            'zip', 'city', 'state', 'country']
        addressStreetAddress = request.form.get('addressStreetAddress')
        addressApartmentOrSuite = request.form.get('addressApartmentOrSuite')
        addressZip = request.form.get('addressZip')
        addressCity = request.form.get('addressCity')
        addressState = request.form.get('addressState')
        addressCountry = request.form.get('addressCountry')

        shipping_payload = (addressStreetAddress, addressApartmentOrSuite,
                            addressCity, addressZip, addressState, addressCountry, str(1))

        formatted_shipping = zip(SHIPPING_HEADERS, shipping_payload[:-1])
        formatted_shipping_payload = {table_headers: val for (
            table_headers, val) in formatted_shipping}

        if SHIPPING_IDENT is None:
            session['new_shipping'] = shipping_payload
            session['shipping_state'] = addressState
            session['shipping_payload'] = formatted_shipping_payload

            if REMEMBER_SHIPPING is not None and int(REMEMBER_SHIPPING) != 0:
                session['shipping_remember'] = True
            else:
                session['shipping_remember'] = False

        else:
            shipping_id = SHIPPING_IDENT
            session['shipping'] = shipping_id
            session['shipping_state'] = request.form.get('SHIPPING_STATE')
            shipping_query = 'SELECT * FROM address WHERE id = %s'
            cursor.execute(shipping_query, shipping_id)

            header = [desc[0] for desc in cursor.description][1:-1]
            results = cursor.fetchall()[0][1:-1]
            formatted_results = zip(header, results)
            shipping_payload = {table_headers: val for (
                table_headers, val) in formatted_results}
            session['shipping_payload'] = shipping_payload

        conn.commit()
        conn.close()
        return redirect(url_for('user_bp.billing_checkout'))


@user_bp.route('/checkout/billing/', methods=['POST', 'GET'])
@login_required(session)
@secure_checkout(session)
@cart_session(session)
@remember_me(session)
@user_only(session)
def billing_checkout():
    if len(session['shopping_cart']) == 0:
        return redirect(url_for('common_bp.landing_page'))

    conn = mysql.connect()
    cursor = conn.cursor()

    if request.method == 'GET':
        payment_payload = {}

        payment_query = '''
                SELECT pm.id, street1, street2, city, zip, state, country, firstName, lastName, cardNumber, cardType, 
                expirationDate
                FROM user_paymentmethod upm
                JOIN payment_method pm ON upm.paymentID_pm_FK = pm.id
                JOIN address a ON pm.billingAddress_addr_FK = a.id
                WHERE upm.userID_pm_FK = (SELECT id FROM user WHERE email = %s)'''

        cursor.execute(payment_query, (session['email']))
        results = cursor.fetchall()
        for i in results:
            payment_payload[i[0]] = {
                'street1': i[1],
                'street2': i[2],
                'city': i[3],
                'zip': i[4],
                'state': i[5],
                'country': i[6],
                'card_fname': i[7].upper(),
                'card_lname': i[8].upper(),
                'card_number': fernet.decrypt(
                    i[9].encode('utf-8')).decode('utf-8')[-4:],
                'card_type': i[10],
                'card_expiry': str(i[11].year) + '-' + str(i[11].month).zfill(2)
            }

        x = get_books(cursor)

        sub_total = x['sub_total']
        shipping_price = "{:.2f}".format(
            calculate_shipping(x['book_quantity']))
        sales_tax = "{:.2f}".format(SALES_TAX[session['shipping_state']])
        grand_total = "{:.2f}".format(
            float(sub_total) + float(shipping_price) + float(sales_tax))

        conn.close()
        return render_template('checkout/billingCheckout.html',
                               billing_payload=payment_payload,
                               book_payload=x['book_payload'],
                               sub_total=sub_total,
                               shipping_price=shipping_price,
                               sales_tax=sales_tax,
                               grand_total=grand_total)
    elif request.method == 'POST':
        PAYMENT_IDENT = request.form.get('PAYMENT_IDENT')
        REMEMBER_PAYMENT = request.form.get('REMEMBER_PAYMENT')

        checkoutCardHolderFirstName = request.form.get('cardHolderFirstName')
        checkoutCardHolderLastName = request.form.get('cardHolderLastName')
        try:
            ccn = fernet.encrypt(request.form.get('ccn').encode('utf-8'))
        except:
            ccn = ''
        ct = request.form.get("CCNProvider")
        ccexp = request.form.get('ccexp')
        if ccexp is not None:
            ccexp += '-01'

        BILLING_HEADERS = ['street1', 'street2',
                           'zip', 'city', 'state', 'country']
        billingStreetAddress = request.form.get('billingStreetAddress')
        billingApartmentOrSuite = request.form.get('billingApartmentOrSuite')
        billingAddressZip = request.form.get('billingAddressZip')
        billingAddressCity = request.form.get('billingAddressCity')
        billingAddressState = request.form.get('billingAddressState')
        billingAddressCountry = request.form.get('billingAddressCountry')

        # PAYMENT PAYLOAD CREATED AFTER BILLING_PAYLOAD HAS BEEN INSERTED
        billing_payload = (billingStreetAddress, billingApartmentOrSuite, billingAddressCity,
                           billingAddressZip, billingAddressState, billingAddressCountry, str(2))
        formatted_billing = zip(BILLING_HEADERS, billing_payload[:-1])
        formatted_billing_payload = {table_headers: val for (
            table_headers, val) in formatted_billing}

        # IF USING NEW SHIPPING ADDRESS
        if PAYMENT_IDENT is None:
            session['new_billing'] = billing_payload

            PAYMENT_HEADERS = ['firstname',
                               'lastname', 'cardNumber', 'cardType']
            payment_payload = [checkoutCardHolderFirstName,
                               checkoutCardHolderLastName, ccn, ct, ccexp, 0]
            formatted_results = zip(PAYMENT_HEADERS, payment_payload[:-1])
            formatted_payment_payload = {table_headers: val for (
                table_headers, val) in formatted_results}

routes/user/templates/checkout/baseCheckout.html
{% extends "base.html" %}
{% block base_title %}Checkout - {% block child_title %}{% endblock %}{% endblock %}

{% block base_head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="/static/user/css/checkout.css">
{% endblock %}

{% block mainTitle %}
    <div class="text-left" id="welcome">
        <p class="primary-lg" id="account-holder">Checkout - {% block title %}{% endblock %}</p>
    </div>
{% endblock %}
<!-- Page Content -->
{% block main %}
    <div class="container wow fadeIn">
        <div class="row">
            <div class="col-lg-7 col-xl-8 col-xxl-9 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h3 class="complement-bold mb-4 card-title">{% block card_title %}{% endblock %}</h3>
                        {% block card_content %}
                        {% endblock %}
                    </div>
                    <div class="card-footer">
                        {% block card_footer %}
                        {% endblock %}
                    </div>
                </div>
            </div>

            <div class="col-lg-5 col-xl-4 col-xxl-3 mb-4" id="page-wrap">
                <div id="sidebar">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                        <span class="badge blue-gradient badge-pill"> {{ book_payload.keys()|length }}</span>
                    </h4>
                    <!-- Cart -->
                    <ul class="list-group mb-3 z-depth-1 cart-items">
                        {% for isbn, payload in book_payload.items() %}
                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div>
                                    <h6 class="my-0 complement">{{ payload['title'] }}<small>
                                        x{{ payload['quantity'] }}</small></h6>
                                    <small class="text-muted"><i
                                            class="checkoutSideBarISBN">ISBN: {{ isbn }}</i></small>
                                    <h6 class="my-0 complement">
                                        <small class="text-muted"><i>${{ payload['price'] }} each</i></small>
                                    </h6>

                                </div>
                                <span class="text-muted complement">$<span
                                        class="sidebar-item-price pl-0">{{ "{:,.2f}".format(payload['total_price']) }}</span></span>
                            </li>
                        {% endfor %}
                        <li class="list-group-item d-flex justify-content-between" id="subtotalListElement">
                            <span class="complement-bold">Subtotal</span>
                            <strong class="primary-sm">$<span id="subtotal">{{ sub_total }}</span></strong>
                        </li>
                        {% block add_list_item %}
                        {% endblock %}

                    </ul>
                    <!-- Cart -->
                    <!-- Promo code -->
                    {% block below_cart_item %}
                    {% endblock %}

                    <a href="{{ url_for('common_bp.shopping_cart') }}">
                        <button class="btn btn-outline-primary btn-block rounded waves-effect waves-ripple mt-3"
                                id="backToCartBtn" type="button">
                            <i class="fa fa-chevron-left"></i>
                            Back to Cart
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% block add_script %}
    {% endblock %}

    <script>
        $(document).scroll(function () {
            if ($(window).width() >= 992) {
                var y = $(document).scrollTop(),
                    header = $("#sidebar");
                if (y >= (y + $('.card').offset().top)) {
                    header.css({"position": "static", "width": "auto"});
                } else {
                    header.css({"position": "sticky", "width": "auto", "top": "20px"});
                }
            }
        });

    </script>
{% endblock %}

routes/user/templates/checkout/orderConf.html
{% extends "baseConfirm.html" %}
{% block title %}Order Confirmation{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block cardTitle %}
    Thank you! Your order has been recorded.
{% endblock %}

{% block content %}
    We will send you a confirmation containing your order number: {{ order_num }}.
{% endblock %}

{% block card_footer %}
    {#    #}
{% endblock %}

routes/user/templates/checkout/reviewOrder.html
{% extends "checkout/baseCheckout.html" %}
{% block child_title %}Shipping{% endblock %}

{% block base_head %}
    {{ super() }}
    <style>
        p.shipping-entries, p.billing-entries {
            margin-bottom: 0.2rem;
        }
    </style>
{% endblock %}

{% block title %}Review{% endblock %}

{% block card_title %}
    Review Your Order
{% endblock %}
{% block card_content %}
    <div class="d-none" nile-form-action="{{ url_for('user_bp.review_checkout') }}" id="dummy"></div>
    <div class="row">
        <div class="col">
            <div class="shipping-entries">
                <div class="heading-group d-inline-block mb-3">
                    <span class="complement-bold mr-2">Shipping Address</span>
                    <a href="{{ url_for('user_bp.shipping_checkout') }}">Edit</a>
                </div>
                <p class="shipping-entries" id="street1">{{ shipping_payload['street1'] }}</p>
                {% if 'street2' in shipping_payload %}
                    <p class="billing-entries" id="street2">{{ shipping_payload['street2'] }}</p>
                {% endif %}<p class="shipping-entries" id="zip">{{ shipping_payload['zip'] }}</p>
                <span class="shipping-entries" id="city">{{ shipping_payload['city'] }}, </span>
                <span class="shipping-entries" id="state">{{ shipping_payload['state'] }}</span>
                <p class="shipping-entries" id="country">{{ shipping_payload['country'] }}</p>
            </div>
        </div>
        <div class="col">
            <div class="billing-entries">
                <div class="heading-group d-inline-block mb-3">
                    <span class="complement-bold mr-2">Payment Method</span>
                    <a href="{{ url_for('user_bp.billing_checkout') }}">Edit</a>
                </div>
                <div class="row">
                    <div class="col">

                        <div class="d-block">
                            <small class="text-muted d-block">Card Information</small>
                            <div class="d-block">
                                <span class="shipping-entries" id="cardFirst">{{ payment_payload['firstname'] }}</span>
                                <span class="shipping-entries" id="cardLast">{{ payment_payload['lastname'] }}</span>
                            </div>
                            <div class="d-block">
                                <span class="shipping-entries" id="cardType">{{ payment_payload['cardType'] }}</span>
                                <span class="shipping-entries" id="cardLast4">{{ payment_payload['cardNumber'] }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <small class="text-muted d-block">Billing Address</small>
                        <p class="billing-entries" id="street1">{{ billing_payload['street1'] }}</p>
                        {% if 'street2' in billing_payload %}
                            <p class="billing-entries" id="street2">{{ billing_payload['street2'] }}</p>
                        {% endif %}
                        <!-- ONLY IF A STREET 2 EXISTS!!! -->
                        <p class="billing-entries" id="zip">{{ billing_payload['zip'] }}</p>
                        <span class="shipping-entries" id="city">{{ billing_payload['city'] }}, </span>
                        <span class="shipping-entries" id="state">{{ billing_payload['state'] }}</span>
                        <p class="billing-entries" id="country">{{ billing_payload['country'] }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block card_footer %}
    <button type="button" id="placeOrder" class="btn blue-gradient btn-lg btn-block waves-effect waves-ripple">Place
        Order
    </button>
{% endblock %}


{% block add_list_item %}
    <li class="list-group-item d-flex justify-content-between">
        <span class="complement">Shipping Cost</span>
        <strong class="text-danger">+ $<span class="sidebar-item-price pl-0"
                                             id="shippingTotal">{{ shipping_price }}</span></strong>
    </li>
    <li class="list-group-item d-flex justify-content-between" id="salesTaxListElement">
        <span class="complement">Sales Tax</span>
        <strong class="text-danger">+ $<span id="salesTax">{{ sales_tax }}</span></strong>
    </li>
    <li class="list-group-item d-flex justify-content-between">
        <span class="complement-bold">GRAND TOTAL (USD)</span>
        <strong class="primary-md">$<span id="checkoutTotalPrice">{{ grand_total }}</span></strong>
    </li>
{% endblock %}

{% block below_cart_item %}
    <form id="addPromoForm" method="POST">
        <div class="card p-2 promo-card">
            <div class="input-group md-outline md-form" id="promoCodeInputGroup">
                <input type="text" class="form-control" id="promoCodeInput" required
                       style="text-transform: uppercase;">
                <div class="input-group-append">
                    <button class="btn blue-gradient btn-md waves-effect m-0 ml-2" id="promoBtn"
                            type="submit">Redeem
                    </button>
                </div>
                <label for="promoCodeInput">Promo Code</label>
            </div>
        </div>
    </form>
{% endblock %}

{% block add_script %}
    <script src="/static/user/js/checkout/review.js" type="module"></script>
{% endblock %}

routes/user/templates/checkout/shippingCheckout.html
{% extends "checkout/baseCheckout.html" %}
{% block child_title %}Shipping{% endblock %}

{% block base_head %}
    {{ super() }}
{% endblock %}

{% block title %}First, Shipping.{% endblock %}

{% block card_title %}
    Shipping Information
{% endblock %}
{% block card_content %}
    <div class="d-inline-block w-100">
        <div class="custom-control custom-radio mr-2 d-inline-block">
            <input type="radio" class="custom-control-input" id="chooseShippingToggle"
                   name="shippingToggleGroup" checked>
            <label class="custom-control-label mb-2" for="chooseShippingToggle"
                   id="chooseShippingToggleLabel">Choose a Shipping
                Address</label>
        </div>
        <a data-toggle="collapse" class="float-right" data-target="#addressEntry"
           href=""
           id="addressToggler">View</a>
    </div>
    <label for="shippingAddressSelect" class="d-none"></label>
    {% if shipping_payload|length != 0 %}
        <select class="custom-select d-block w-100 mb-3 checkout-select"
                id="shippingAddressSelect">
            {% for id,payload in shipping_payload.items() %}
                <option nile-shipping-street1="{{ payload['street1'] }}"
                        nile-shipping-street2="{{ payload['street2'] }}"
                        nile-shippping-zip="{{ payload['zip'] }}"
                        nile-shipping-city="{{ payload['city'] }}"
                        nile-shipping-state="{{ payload['state'] }}"
                        nile-shipping-country="{{ payload['country'] }}"
                        nile-shipping-ident="{{ id }}">

                    {{ payload['street1'] }} {{ payload['street2'] }}
                </option>
            {% endfor %}
        </select>
    {% endif %}

    <div class="ship-radio-holder">
        <div class="custom-control custom-radio mr-2">
            <input type="radio" class="custom-control-input" id="enterAddressToggle"
                   name="shippingToggleGroup">
            <label class="custom-control-label mb-2" for="enterAddressToggle">New
                Shipping
                Address</label>
        </div>
    </div>

    <div id="addressEntry" class="collapse checkout-readonly">
        <small>
            <span class="text-muted font-italic ml-2 mb-1">Shipping Information</span>
        </small>
        <small class="float-right">
            <a href="{{ url_for('user_bp.shipping_address') }}"
               class="font-italic mr-1">Edit
                Information</a>
        </small>
        <div class="card-specific">
            <div class="form-row">
                <div class="col">
                    <div class="form-group md-form md-outline">
                        <input type="text" class="form-control"
                               id="checkoutAddressStreetAddress"
                               name="addressStreetAddress"
                               maxlength="45"
                               required>
                        <label for="checkoutAddressStreetAddress">Street Address</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="form-group md-form md-outline">
                        <input type="text" class="form-control"
                               id="checkoutAddressApartmentOrSuite"
                               maxlength="45"
                               name="addressApartmentOrSuite">
                        <label for="checkoutAddressApartmentOrSuite">Apartment or
                            Suite</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="form-group md-form md-outline">
                        <input type="text" class="form-control" id="checkoutAddressZip"
                               maxlength="10"
                               name="addressZip">
                        <label for="checkoutAddressZip">ZIP or Postal code</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-5">
                    <div class="form-group md-form md-outline">
                        <input type="text" class="form-control" id="checkoutAddressCity"
                               required
                               maxlength="45"
                               name="addressCity">
                        <label for="checkoutAddressCity">City</label>
                    </div>
                </div>
                <div class="form-group col-md-2" style="margin-top: 8px">
                    <label for="checkoutAddressState" class="d-none">State</label>
                    <select id="checkoutAddressState"
                            class="form-control" required
                            name="addressState">
                        <option value="" disabled selected>State</option>
                        <option value="GA">GA</option>
                        <option value="CA">CA</option>
                    </select>

                </div>
                <div class="form-group col-md-5" style="margin-top: 8px">
                    <label for="checkoutAddressCountry" class="d-none">Country</label>
                    <select id="checkoutAddressCountry"
                            class="form-control"
                            required
                            name="addressCountry">
                        <option value="" disabled selected>Country</option>
                        <option value="United States">United States</option>
                    </select>
                </div>
            </div>
        </div>
    </div>


    <div id="newAddressEntry" class="collapse">
        <div class="custom-control custom-checkbox my-2">
            <input type="checkbox" class="custom-control-input remember-me"
                   id="rememberShipping"
                   value="0">
            <label class="custom-control-label" for="rememberShipping">Remember this
                next
                time</label>
        </div>
        <small>
            <span class="text-muted font-italic ml-2 mb-1">Shipping Information</span>
        </small>
        <div class="card-specific">
            <form action="{{ url_for(request.endpoint) }}" id="dummyForm">
                <div class="form-row">
                    <div class="col">
                        <div class="form-group md-form md-outline">
                            <label for="newAddressStreetAddress">New Address</label>
                            <input type="text" class="form-control"
                                   id="newAddressStreetAddress"
                                   name="addressStreetAddress"
                                   maxlength="45"
                                   required>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <div class="form-group md-form md-outline">
                            <label for="newAddressApartmentOrSuite">Apartment or
                                Suite</label>
                            <input type="text" class="form-control valid"
                                   id="newAddressApartmentOrSuite"
                                   maxlength="45"
                                   name="addressApartmentOrSuite">
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <div class="form-group md-form md-outline">
                            <label for="newAddressZip">ZIP or Postal code</label>
                            <input type="text" class="form-control" id="newAddressZip"
                                   maxlength="10"
                                   required
                                   name="addressZip">
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-5">
                        <div class="form-group md-form md-outline">
                            <label for="newAddressCity">City</label>
                            <input type="text" class="form-control" id="newAddressCity"
                                   maxlength="45"
                                   required
                                   name="addressCity">
                        </div>
                    </div>
                    <div class="form-group col-md-2" style="margin-top: 8px">
                        <label for="newAddressState" class="d-none">State</label>
                        <select id="newAddressState"
                                class="form-control" required
                                name="addressState">
                            <option value="" disabled selected>--</option>
                            <option value="GA">GA</option>
                            <option value="CA">CA</option>
                        </select>

                    </div>
                    <div class="form-group col-md-5" style="margin-top: 8px">
                        <label for="newAddressCountry" class="d-none">Country</label>
                        <select id="newAddressCountry"
                                class="form-control"
                                required
                                name="addressCountry">
                            <option value="" disabled selected>--</option>
                            <option value="United States">United States</option>
                        </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block card_footer %}
    <button type="button" id="contToPayBtn" class="btn blue-gradient btn-lg btn-block waves-effect waves-ripple">
        Continue to Payment
    </button>
{% endblock %}

{% block add_script %}
    <script src="/static/user/js/checkout/shippingCheckout.js" type="module"></script>
{% endblock %}