routes/admin/routes.py
from flask import Blueprint, render_template, request, redirect, flash, session, url_for, jsonify
from functools import wraps
import bcrypt
from server import mysql
import sys
import string

from routes.common.util import remember_me, cart_session
from routes.user.routes import send_change_conf_email, get_subscription
from routes.admin.util import admin_required, send_promo_email

admin_bp = Blueprint('admin_bp', __name__,
                     template_folder='templates', static_folder='static')


@admin_bp.route('/overview/')
@admin_required(session)
@remember_me(session)
def overview():
    return render_template('./adminOverview.html')


@admin_bp.route('/change_name/', methods=['GET', 'POST'])
@admin_required(session)
@remember_me(session)
def change_name():
    if request.method == 'GET':
        return render_template('adminChangeName.html')
    else:
        conn = mysql.connect()
        cursor = conn.cursor()

        fname = request.form.get('inputFirstname')
        firstLetter = fname[0].upper()
        fname = firstLetter + fname[1:].lower()

        lname = request.form.get('inputLastname')
        firstLetter = lname[0].upper()
        lname = firstLetter + lname[1:].lower()

        session['firstName'] = fname
        cursor.execute('UPDATE admin SET firstname = %s WHERE email = %s', (fname, session['email']))
        conn.commit()

        session['lastName'] = lname
        cursor.execute('UPDATE admin SET lastname = %s WHERE email = %s', (lname, session['email']))
        conn.commit()

        conn.close()

        send_change_conf_email(session['email'], session['firstName'])

        flash('Your information has been recorded.')
        return redirect(url_for('admin_bp.change_name'))


@admin_bp.route('/change_pass/', methods=['GET', 'POST'])
@admin_required(session)
@remember_me(session)
def change_pass():
    if request.method == 'POST':
        conn = mysql.connect()
        cursor = conn.cursor()

        new_password = request.form.get('newPassword')
        confirm_new_password = request.form.get('confirmNewPassword')

        if new_password != confirm_new_password:
            return jsonify({'Response': 400})
        else:
            new_password = bcrypt.hashpw(
                new_password.encode('utf-8'), bcrypt.gensalt())

            cursor.execute('UPDATE admin SET pass=%s WHERE email=%s', (new_password, session['email']))
            conn.commit()
            conn.close()

            send_change_conf_email(session['email'], session['firstName'])

            flash('Your information has been recorded.')
            return redirect(url_for('admin_bp.change_pass'))
    else:
        return render_template('adminChangePassword.html')


@admin_bp.route('/manage_books/')
@admin_required(session)
@remember_me(session)
def manage_books():
    return render_template('./adminManageBooks.html')


@admin_bp.route('/manage_promotions/')
@admin_required(session)
@remember_me(session)
def manage_promotions():
    return render_template('./adminManagePromotions.html')


@admin_bp.route('/manage_users/')
@admin_required(session)
@remember_me(session)
def manage_users():
    return render_template('./adminManageUsers.html')


@admin_bp.route('/manage_books/mbooksf/', methods=['GET', 'POST'])
@admin_required(session)
@remember_me(session)
def add_books_form():
    if request.method == 'POST':
        book_title = string.capwords(request.form.get('bookTitle')).strip()
        isbn = request.form.get('isbn').replace("-", "").strip()
        author_firstname = string.capwords(request.form.get('authorFirstName')).strip()
        author_lastname = string.capwords(request.form.get('authorLastName')).strip()
        edition = request.form.get('edition').strip()
        publisher = request.form.get('publisher').strip()
        genre = request.form.get('genre').strip()
        p_type = request.form.get('productType').strip()
        num_pages = request.form.get('numPages').strip()
        date_published = request.form.get('datePublished').strip()
        recv_stock = request.form.get('recvStock').strip()
        binding_type = request.form.get('bindingType').strip()
        price = request.form.get('price').strip()
        cover_id = request.form.get('coverID').strip()
        book_summary = request.form.get('bookSummary').strip()

        print(cover_id, file=sys.stderr)
        conn = mysql.connect()
        cursor = conn.cursor()
        query = """
        INSERT INTO book (ISBN, bindingID_book_FK, genreID_book_FK, typeID_book_FK, title, price, numPages, nile_cover_ID,
        edition, publisher, publicationDate, stock, authorFirstName, authorLastName, summary)
        VALUES (
        %s,
        (SELECT id FROM binding WHERE binding = %s),
        (SELECT id FROM genre WHERE genre = %s),
        (SELECT id from product_type where type = %s),
        %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s, %s)
        """

        try:
            cursor.execute(query, (isbn, binding_type, genre, p_type, book_title, price, num_pages, cover_id, edition,
                                   publisher, date_published, recv_stock, author_firstname, author_lastname,
                                   book_summary))
            conn.commit()
            conn.close()
        except Exception as e:
            flash('Book already exists in the database')
            return redirect(url_for('admin_bp.add_books_form'))

        flash('Book has been successfully added.')
        return redirect(url_for('admin_bp.add_books_form'))

    return render_template('./forms/manage_books_form.html')


@admin_bp.route('/manage_promotions/epromof/', methods=['GET', 'POST'])
@admin_required(session)
@remember_me(session)
def edit_promo_form():
    if request.method == 'POST':
        promo_id = request.form.get('promoId')

        conn = mysql.connect()
        cursor = conn.cursor()

        query = """
                SELECT * FROM promotion WHERE ID=%s
                """
        cursor.execute(query, promo_id)
        results = cursor.fetchall()
        conn.close()

        if len(results) == 0:
            flash('A promotion with that ID does not exists.')
            return render_template('./forms/edit_promo_form.html')
        else:
            return render_template('./forms/edit_promo_form.html', id=results[0][0],
                                   name=results[0][2], code=results[0][1],
                                   discount=format(results[0][3], ".0%"),
                                   endDate=results[0][5], notes=results[0][6])

    return render_template('./forms/edit_promo_form.html')


@admin_bp.route('/manage_promotions/apromof/', methods=['GET', 'POST'])
@admin_required(session)
@remember_me(session)
def add_promo_form():
    if request.method == 'POST':
        promo_name = request.form.get('promoName')
        promo_code = request.form.get('promoCode').upper()
        promo_amt = float(request.form.get('promoAmt')) / 100
        promo_start = request.form.get('promoStart')
        promo_expiry = request.form.get('promoExpiry')
        promo_notes = request.form.get('promoNotes')

        conn = mysql.connect()
        cursor = conn.cursor()

        query = """
                INSERT INTO promotion (code, name, discount, startDate, endDate, notes)
                VALUES (%s, %s, %s, %s, %s, %s)
                """
        try:
            cursor.execute(query, (promo_code, promo_name, promo_amt, promo_start, promo_expiry, promo_notes))

            subscribed_users_query = 'SELECT firstname, email FROM user WHERE isSubscribed = 1'
            cursor.execute(subscribed_users_query)

            results = cursor.fetchall()
            conn.commit()
            conn.close()
        except Exception as e:
            flash('A promotion with this code already exists.')
            return redirect(url_for('admin_bp.add_promo_form'))

        for result in results:
            send_promo_email(recipient=result[1], recipient_fname=result[0], promo_code=promo_code,
                             promo_amount=promo_amt, url=request.url_root)

        flash('Promotion has been successfully added.')

        return redirect(url_for('admin_bp.add_promo_form'))

    return render_template('./forms/add_promo_form.html')


@admin_bp.route('/manage_users/eusrf/')
@admin_required(session)
@remember_me(session)
def edit_users_form():
    return render_template('./forms/edit_users_form.html')


@admin_bp.route('/settings/', methods=['POST', 'GET'])
@remember_me(session)
@admin_required(session)
def settings():
    if request.method == 'GET':
        conn = mysql.connect()
        cursor = conn.cursor()
        subscription = int.from_bytes(get_subscription(cursor, session['email'], True), 'big')

        if subscription == 1:
            return render_template('adminSubscription.html', subscription="checked")
        else:
            return render_template('adminSubscription.html', subscription="")
    elif request.method == 'POST':
        conn = mysql.connect()
        cursor = conn.cursor()

        flag = request.form.get("flag")

        # USER IS SUBSCRIBING
        if flag == 'SUBSCRIBE':
            query = 'UPDATE admin SET isSubscribed = %s WHERE email = %s'
            cursor.execute(query, (1, session['email']))

            conn.commit()
            conn.close()
            return jsonify({'response': 200})

        # USER IS UNSUBSCRIBING
        elif flag == 'UNSUBSCRIBE':
            query = 'UPDATE admin SET isSubscribed = %s WHERE email = %s'
            cursor.execute(query, (0, session['email']))

            conn.commit()
            conn.close()
            return jsonify({'response': 200})

routes/admin/templates/add_books.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Books</title>

    {% include 'common_links.html' %}

    <link rel="stylesheet" type="text/css" href="../../../static/user/css/common.css">
    <link rel="stylesheet" type="text/css" href="../../../static/user/css/nav.css">
</head>

<body class="our-color">
{% include 'nav.html' %}
<div class="container">
    <div class="row mt-xl-5" id="cust-info">
        <div class="col mb-5">
            <div class="text-left" id="welcome">
                <p class="primary-lg" id="account-holder">Add New Books</p>
            </div>
        </div>
    </div>
</div>
<div class="container footer-sep">
    <!--Grid row-->

    <div class="row">
        <!--Grid column-->
        <div class="col mb-4">
            <!-- Card -->
            <div class="card gradient-card h-100">
                <div class="card-image"
                     style="background-image: url(https://mdbootstrap.com/img/Photos/Horizontal/Work/4-col/img%20%2814%29.jpg)">
                    <!-- Content -->
                        <div class="text-white mask card-contextual-info">

                            <div class="row">
                                <div class="col align-self-center">
                                    <div class="first-content p-3">
                                        <h3 class="card-title">Submit the Form</h3>
                                    </div>
                                </div>
                                <div class="col align-self-center">
                                    <div class="second-content pr-3" style="float: right;">
                                        <i class="fas fa-edit fa-3x"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Content -->
                    <div class="card-body white">
                        <form method="POST">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <i class="fas fa-book"></i>
                                    <label for="bookTitle">Book Title</label>
                                    <div class="input-group">
                                        <input name="bookTitle" type="text" class="form-control" id="bookTitle"
                                               placeholder="Book Title"
                                               required>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <i class="fas fa-barcode"></i>
                                    <label for="isbn">ISBN-13</label>
                                    <div class="input-group">
                                        <input name="isbn" type="text" class="form-control" id="isbn"
                                               placeholder="ISBN-13"
                                               required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <i class="fas fa-signature"></i>
                                    <label for="authorFirstName">Author First Name</label>
                                    <div class="input-group">
                                        <input name="authorFirstName" type="text" class="form-control"
                                               id="authorFirstName"
                                               placeholder="Author First Name" required>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <i class="fas fa-signature"></i>
                                    <label for="authorLastName">Author Last Name</label>
                                    <div class="input-group">
                                        <input name="authorLastName" type="text" class="form-control"
                                               id="authorLastName"
                                               placeholder="Author Last Name">
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <i class="fas fa-signature"></i>
                                    <label for="edition">Edition</label>
                                    <div class="input-group">
                                        <input name="edition" type="text" class="form-control" id="edition"
                                               placeholder="Book Edition">
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <i class="fas fa-signature"></i>
                                    <label for="publisher">Publisher</label>
                                    <div class="input-group">
                                        <input name="publisher" type="text" class="form-control" id="publisher"
                                               placeholder="Book Publisher">
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col">
                                    <i class="far fa-laugh-squint"></i>
                                    <label for="genre">Genre</label>
                                    <div class="input-group">
                                        <select name="genre" id="genre" class="form-control">
                                            <option selected>Choose...</option>
                                            <option>Mystery</option>
                                            <option>Horror</option>
                                            <option>Adventure</option>
                                            <option>Fantasy</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col">
                                    <i class="fas fa-list-ol"></i>
                                    <label for="numPages">Number of Pages</label>
                                    <div class="input-group">
                                        <input name="numPages" type="number" class="form-control" id="numPages"
                                               placeholder="Number of Pages">
                                    </div>
                                </div>
                                <div class="form-group col">
                                    <i class="far fa-clock"></i>
                                    <label for="datePublished">Date Published</label>
                                    <div class="input-group">
                                        <input name="datePublished" type="date" class="form-control" id="datePublished"
                                               placeholder="Date Published" required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col">
                                    <i class="fas fa-scroll"></i>
                                    <label for="bindingType">Binding Type</label>
                                    <div class="input-group">
                                        <select name="bindingType" id="bindingType" class="form-control">
                                            <option selected>Paperback</option>
                                            <option>Hardback</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col">
                                    <i class="fas fa-cubes"></i>
                                    <label for="recvStock">Received Stock</label>
                                    <div class="input-group">
                                        <input name="recvStock" type="number" class="form-control" id="recvStock"
                                               placeholder="Received Stock" required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col">
                                    <i class="fas fa-dollar-sign"></i>
                                    <label for="price">Selling Price ($)</label>
                                    <div class="input-group">
                                        <input name="price" step="0.01" type="number" class="form-control" id="price"
                                               placeholder="Selling Price in USD ($)" required>
                                    </div>
                                </div>
                                <div class="form-group col">
                                    <i class="far fa-file-image"></i>
                                    <label for="coverImage">Cover Image</label>
                                    <div class="custom-file">
                                        <input name="coverImage" type="file" class="custom-file-input" id="coverImage"
                                               aria-describedby="coverImage" accept=".png,.jpeg,.gif,.jpg,.heic"
                                               style="cursor: pointer;">
                                        <label class="custom-file-label" for="coverImage">Upload Image</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col">
                                    <i class="fas fa-comment-alt"></i>
                                    <label for="bookSummary">Book Summary</label>
                                    <div class="input-group blue-border-focus">
                                        <textarea name="bookSummary" class="form-control" id="bookSummary" rows="4"
                                                  placeholder="Book Summary" maxlength="500"></textarea>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" id="updateBtn" class="btn blue-gradient btn-block">Create New Book
                                Entry
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="py-5 bg-dark">
        <div class="container text-white">
            <p class="mb-2 text-center">Copyright &copy; Nile 2020</p>
            <div class="text-center">
                <a class="waves-effect waves-light mr-3">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="waves-effect waves-light mr-3">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="waves-effect waves-light">
                    <i class="fab fa-facebook"></i>
                </a>
            </div>
        </div>
        <!-- /.container -->
    </footer>
</body>

</html>

routes/admin/templates/adminBase.html
{% extends "base.html" %}
{% block base_title %}
    Admin - {% block title %}{% endblock %}
{% endblock %}

{% block base_head %}
    {{ super() }}

    {% block head %}
        <style>
            .input-group .btn-outline-warning {
                border-top-right-radius: 5px;
                border-bottom-right-radius: 5px;
            }

            @media (max-width: 991px) {
                #accountListings {
                    margin-bottom: 20px;
                }
            }

            #accountListings > a {
                height: 65px;
            }
        </style>
    {% endblock head %}
{% endblock base_head %}

{% block mainTitle %}
    <div class="text-left" id="welcome">
        <p class="primary-lg" id="account-holder">Welcome Back, <span
                id="name">{{ session['firstName'] }}.</span>
            <span class="badge blue-gradient shadow ml-2">Admin</span></p>
    </div>
{% endblock %}

{% block main %}
    <div class="container footer-sep">
        <div class="row">
            <nav class="col-lg-3">
                <ul class="list-group complement-light" id="accountListings">
                    <a class="list-group-item waves-effect" id="accountOverview" href="{{ url_for('admin_bp.overview') }}">
                        Admin Account Overview
                    </a>
                    <a class="list-group-item waves-effect" id="changeMyName" href="{{ url_for('admin_bp.change_name') }}">
                        Change My Name
                    </a>
                    <a class="list-group-item waves-effect" id="changeMyPass" href="{{ url_for('admin_bp.change_pass') }}">
                        Change My Password
                    </a>
                    <a class="list-group-item waves-effect" id="manageBooks" href="{{ url_for('admin_bp.manage_books') }}">
                        Manage Books & Inventory
                    </a>
                    <a class="list-group-item waves-effect" id="managePromotions" href="{{ url_for('admin_bp.manage_promotions') }}">
                        Manage Promotions
                    </a>
                    <a class="list-group-item waves-effect" id="manageUsers" href="{{ url_for('admin_bp.manage_users') }}">
                        Manage Users
                    </a>
                    <a class="list-group-item waves-effect" id="settings" href="{{ url_for('admin_bp.settings') }}">
                        Account Settings
                    </a>
                </ul>
            </nav> <!-- col.// -->
            <main class="col-lg-9 main-content" id="mainContent">
                {% block content %}
                {% endblock %}
            </main> <!-- col.// -->
        </div>
    </div>

    <script>
        $(function () {
            let x = window.location.href;
            if (x.includes("/admin/overview/")) {
                $("#accountOverview").addClass("active");
            } else if (x.includes("/admin/change_name/")) {
                $("#changeMyName").addClass("active");
            } else if (x.includes("/admin/change_pass/")) {
                $("#changeMyPass").addClass("active");
            } else if (x.includes("/admin/manage_books/")) {
                $("#manageBooks").addClass("active");
            } else if (x.includes("/admin/manage_promotions/")) {
                $("#managePromotions").addClass("active");
            } else if (x.includes("/admin/manage_users/")) {
                $("#manageUsers").addClass("active");
            } else if (x.includes("/admin/settings/")) {
                $("#settings").addClass("active");
            }
        });
    </script>
{% endblock main %}

routes/admin/templates/adminChangeName.html
{% extends "./adminBase.html" %}
{% block title %}Change Name{% endblock %}

{% block head %}
    {{ super() }}
    <style>
        .md-form .form-control {
            margin-bottom: 0;
        }

        .md-form.md-outline {
            margin-top: 0.5rem !important;
        }

        .md-form input:read-only, .card-specific input:read-only {
            background-color: #e9e9e9 !important;
            color: #000000;
        }

        .md-form input:read-only ~ label.active {
            background: transparent !important;
        }

        .form-group i.fas.fa-user {
            position: absolute;
            right: 10px;
            bottom: 6.5px;
        }

        /* Extra Small Devices, Phones */
        @media (max-width: 480px) {
            #editBtn {
                float: none !important;
                display: block !important;
                width: 100% !important;
                margin: 20px 0 20px 0 !important;
            }
        }
    </style>
{% endblock %}

{% block content %}
    <div class="card-image">
        <!-- Content -->
        <a href="#">
            <div class="text-white d-flex h-100 mask card-contextual-info">
                <div class="container-fluid give">
                    <div class="row py-3 pr-3">
                        <div class="col-10">
                            <div class="first-content">
                                <h4 class="card-title complement">My Info</h4>
                            </div>
                        </div>
                        <div class="col-2 align-self-center">
                            <div class="second-content" style="float: right;">
                                <i class="fas fa-user-circle fa-3x"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <!-- Content -->
    <div class="card-body white change-my-name">
        <div class="d-inline-block w-100 ">
            <h4 class="text-uppercase font-weight-bold my-2 d-inline-block" id="nameDetails">Manage your Name</h4>
            <button class="btn nile-yellow-gradient btn-sm my-2 float-right align-content-center waves-effect"
                    id="editBtn">Edit
            </button>
        </div>
        {% with name_change = get_flashed_messages() %}
            {% if name_change %}
                <p class="flashes text-center" style="color: rgb(37, 179, 132);">
                    {% for msg in name_change %}
                        {{ msg }}
                    {% endfor %}
                </p>
            {% endif %}
        {% endwith %}
        <form id="changeNameForm" class="profile-form" method="POST">
            <div class="form-row mb-3">
                <div class="col">
                    <div class="form-group md-form md-outline mb-0" id="inputFirstnameGroup">
                        <input id="inputFirstname" type="text" class="form-control mt-0"
                               placeholder="First Name" readonly aria-readonly="true"
                               aria-label="First Name" name="inputFirstname"
                               maxlength="45"
                               value="{{ session['firstName'] }}">
                        <label for="inputFirstname">First Name</label>
                        <i class="fas fa-user prefix"></i>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="form-group md-form md-outline mb-0" id="inputLastnameGroup">
                        <input id="inputLastname" type="text" class="form-control" placeholder="Last Name"
                               aria-label="Last Name" name="inputLastname"
                               maxlength="45"
                               value="{{ session['lastName'] }}" readonly aria-readonly="true">
                        <label for="inputLastname">Last Name</label>
                        <i class="fas fa-user prefix"></i>
                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col">
                    <!--PLEASE FOR THE LOVE OF GOD CHANGE THIS MARGIN TOP VALUEs-->
                    <button class="btn blue-gradient btn-block" style="margin-top: 30px;" type="submit"
                            id="changeNameBtn">Update
                    </button>
                </div>
            </div>
        </form>
    </div>
    <script type="module" src="/static/user/js/profile/name.js"></script>
{% endblock %}

routes/admin/templates/adminManageUsers.html
{% extends "adminBase.html" %}
{% block title %}Change Name{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="card-image">
        <a href="#">
            <div class="text-white d-flex h-100 mask card-contextual-info">
                <div class="container-fluid give">
                    <div class="row py-3 pr-3">
                        <div class="col-10">
                            <div class="first-content">
                                <h3 class="card-title complement">Manage Users</h3>
                            </div>
                        </div>
                        <div class="col-2 align-self-center">
                            <div class="second-content" style="float: right;">
                                <i class="fas fa-book fa-3x"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    <div class="card-body white change-my-name">
        <h4 class="text-uppercase font-weight-bold my-4">Add new users, promote, or suspend existing
            ones</h4>
        <div class="row">
            <div class="col">
                <label for="manageUserBtn">Manage Users:</label>
                <a href="/admin/manage_users/eusrf/" target="_blank">
                    <button id="manageUserBtn" class="btn blue-gradient btn-block">Manage Users</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}