routes/api/routes.py
from flask import Blueprint, request, render_template, jsonify, redirect, flash, session, url_for
from flaskext.mysql import pymysql
from functools import wraps
from server import mysql
import secrets

from routes.common.routes import get_genres, get_bindings, get_genres_count, get_bindings_count, generate_cursor

api_bp = Blueprint('api_bp', __name__,
                   template_folder='templates', static_folder='static')

api_url = secrets.token_urlsafe(16)

@api_bp.route('/price', methods=['POST'])
def price():
    conn = mysql.connect()
    cursor = conn.cursor()

    min_price = float(request.form.get('min_price'))
    max_price = float(request.form.get('max_price'))

    print(min_price,max_price)

    query = '''SELECT
                title,
                price,
                CONCAT(authorFirstName, ' ', authorLastName) AS author_name,
                ISBN,
                summary,
                publisher,
                publicationDate,
                numPages,
                (SELECT binding FROM binding WHERE binding.id=book.bindingID_book_FK) AS binding,
                (SELECT genre FROM genre WHERE genre.id=book.genreID_book_FK) AS genre,
                (SELECT type FROM product_type WHERE product_type.id=book.typeID_book_FK) AS type,
                nile_cover_ID
                FROM book
                WHERE %s < price AND %s > price'''

    try:
        cursor.execute(query, (min_price, max_price))

        results = cursor.fetchall()
        print(results)

        header = [desc[0] for desc in cursor.description]
        books = [dict(zip(header, result)) for result in results]

        print(books)


        genres = get_genres(cursor)
        genre_counts = get_genres_count(cursor)
        bindings = get_bindings(cursor)
        binding_counts = get_bindings_count(cursor)

        conn.close()
        return render_template('browse.html', books=books, genres=genres, genre_counts=genre_counts, bindings=bindings, binding_counts=binding_counts)
    
    except pymysql.Error as e:
        print(e)
        return redirect(url_for('common_bp.landing_page'))


@api_bp.route('/promo', methods=['POST'])
def validate_promo():
    PROMO_ID = request.form.get('PROMO_IDENT')
    cursor = generate_cursor(mysql)
    cursor.execute('SELECT * FROM promotion WHERE code=%s', PROMO_ID)

    if cursor.rowcount:
        results = cursor.fetchall()[0]
        return jsonify({'code': PROMO_ID, 'value': results[3]})
    else:
        print('promo doesnt exist')
        return jsonify({"code": False})


@api_bp.route('/'+api_url+'/isbn/', methods=['GET'])
def query_isbn(search_query=None):
    if request.args is None:
        return redirect(url_for('common_bp.landing_page'))
    else:
        if len(request.args) == 1:
            try:
                conn = mysql.connect()
                cursor = conn.cursor()

                isbn = request.args['inputISBN']
                query = '''SELECT 
                    title,
                    price,
                    CONCAT(authorFirstName, ' ', authorLastName) AS author_name,
                    ISBN,
                    summary,
                    publisher,
                    publicationDate,
                    numPages,
                    (SELECT binding FROM binding WHERE binding.id=book.bindingID_book_FK) AS binding,
                    (SELECT genre FROM genre WHERE genre.id=book.genreID_book_FK) AS genre,
                    (SELECT type FROM product_type WHERE product_type.id=book.typeID_book_FK) AS type,
                    nile_cover_ID
                    FROM book
                    WHERE book.ISBN=%s ORDER BY title'''
                cursor.execute(query, (isbn))
                results = cursor.fetchall()

                header = [desc[0] for desc in cursor.description]
                books = [dict(zip(header, result)) for result in results]

                genres = get_genres(cursor)
                genre_counts = get_genres_count(cursor)
                bindings = get_bindings(cursor)
                binding_counts = get_bindings_count(cursor)

                conn.close()
                return render_template('browse.html', books=books, genres=genres, genre_counts=genre_counts, bindings=bindings, binding_counts=binding_counts)

            except pymysql.Error as e:
                print(e)
                return redirect(url_for('common_bp.landing_page'))


@api_bp.route('/'+api_url, methods=['GET'])
def query_books(search_query=None):
    if request.args is None:
        return redirect(url_for('common_bp.landing_page'))
    else:
        conn = mysql.connect()
        cursor = conn.cursor()

        # searching using nav search (search filter + query)
        if len(request.args) == 2:
            try:
                search_filter = request.args['searchFilter']

                if search_filter == 'all':
                    books = general_search(
                        request.args['search_query'], cursor)

                elif search_filter == 'productType':
                    query = '''SELECT 
                    title,
                    price,
                    CONCAT(authorFirstName, ' ', authorLastName) AS author_name,
                    ISBN,
                    summary,
                    publisher,
                    publicationDate,
                    numPages,
                    (SELECT binding FROM binding WHERE binding.id=book.bindingID_book_FK) AS binding,
                    (SELECT genre FROM genre WHERE genre.id=book.genreID_book_FK) AS genre,
                    (SELECT type FROM product_type WHERE product_type.id=book.typeID_book_FK) AS type,
                    nile_cover_ID
                    FROM book
                    WHERE book.typeID_book_FK=(SELECT id FROM product_type WHERE type=%s) ORDER BY title'''
                    cursor.execute(query, (search_query))
                    results = cursor.fetchall()

                    header = [desc[0] for desc in cursor.description]
                    books = [dict(zip(header, result)) for result in results]
                    print(books)

                genres = get_genres(cursor)
                genre_counts = get_genres_count(cursor)
                bindings = get_bindings(cursor)
                binding_counts = get_bindings_count(cursor)

                conn.close()
                return render_template('browse.html', books=books, genres=genres, genre_counts=genre_counts, bindings=bindings, binding_counts=binding_counts)
            except pymysql.Error as e:
                print(e)
                return redirect(url_for('common_bp.landing_page'))

        # using footer search (search query)
        elif len(request.args) == 1:
            books = general_search(request.args['search_query'], cursor)
            genres = get_genres(cursor)
            genre_counts = get_genres_count(cursor)
            bindings = get_bindings(cursor)
            binding_counts = get_bindings_count(cursor)

            conn.close()
            return render_template('browse.html', books=books, genres=genres, genre_counts=genre_counts, bindings=bindings, binding_counts=binding_counts)
        else:
            return redirect(url_for('common_bp.landing_page'))


def general_search(search_query, cursor):
    search_query = request.args['search_query']

    query = '''SELECT 
                    title,
                    price,
                    CONCAT(authorFirstName, ' ', authorLastName) AS author_name,
                    ISBN,
                    summary,
                    publisher,
                    publicationDate,
                    numPages,
                    (SELECT binding FROM binding WHERE binding.id=book.bindingID_book_FK) AS binding,
                    (SELECT genre FROM genre WHERE genre.id=book.genreID_book_FK) AS genre,
                    (SELECT type FROM product_type WHERE product_type.id=book.typeID_book_FK) AS type,
                    nile_cover_ID
                    FROM book ORDER BY title'''
    cursor.execute(query)
    results = cursor.fetchall()

    header = [desc[0] for desc in cursor.description]
    payload = [dict(zip(header, result)) for result in results]
    books = [book for book in payload if search_query.lower() in str(
        book.values()).lower()]

    return books

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block base_head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="4050 Software Engineering Project">
        <meta name="author" content="Manu Puduvalli | Samuel Yuen | Glen George | Lok Kwong | Vrund Parikh">
        <title>{% block base_title %}{% endblock %} - Nile</title>

        {% include 'common_links.html' %}
        <style>

            @media (min-width: 1400px) {
                .main-content-container > .container, #titleGroup1 {
                    max-width: 1300px !important;
                }
            }

            @media (min-width: 1500px) {
                .main-content-container > .container, #titleGroup1 {
                    max-width: 1400px !important;
                }
            }

            @media (min-width: 1600px) {
                .main-content-container > .container, #titleGroup1 {
                    max-width: 1500px !important;
                }
            }

            @media (min-width: 1700px) {
                .main-content-container > .container, #titleGroup1 {
                    max-width: 1600px !important;
                }
            }

            @media (min-width: 1800px) {
                .main-content-container > .container, #titleGroup1 {
                    max-width: 1700px !important;
                }
            }

            @media (min-width: 1900px) {
                .main-content-container > .container, #titleGroup1 {
                    max-width: 1800px !important;
                }
            }

            @media (max-width: 992px) {
                .footer-explanation {
                    border: none !important;
                    padding-right: 15px !important;
                }

                .reg-for-free {
                    padding-bottom: 20px;
                }

                .title-holder {
                    padding-right: 15px !important;
                }

                .left-border {
                    padding-left: 15px !important;
                }
            }


            footer .rel-links a:hover {
                background: linear-gradient(40deg, rgba(69, 202, 252, 0.9), rgba(48, 63, 159, 0.9)) !important;
                border: 1.5px solid;
                border-radius: 5px;
                -webkit-transition: all .01s ease;
            }

            footer .rel-links a {
                padding: 10px;
            }

            .right-border {
                padding-right: 55px;
            }

            .left-border {
                padding-left: 55px;
            }

            .main-footer-content {
                max-width: calc(100vw - 150px) !important;
            }


        </style>
    {% endblock %}
</head>
<body class="our-color">
<div class="pb-5">
    <!-- Navigation -->
    {% include 'nav.html' %}
</div>

{% set titleable = true %}

{% block show_title %}
    {% if titleable %}
        <div class="container" id="titleGroup1">
            <div class="row">
                <div class="col mb-4">
                    {% block mainTitle %}
                    {% endblock %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock show_title %}

<!-- Page Content -->
<div class="footer-sep main-content-container" id="mainContent">
    {% block main %}
    {% endblock %}
</div>
<footer class="page-footer font-small bg-dark pt-4">
    <div class="container text-md-left main-footer-content">
        <div class="row">
            <div class="col-md-6 mx-auto pr-0">
                <div class="text-center right-border title-holder">
                    <h5 class="text-uppercase primary-md"
                        style="letter-spacing: 4px;"><a href="https://www.nilebookstore.com">Nile</a></h5>
                    <hr class="blue darken-3 accent-2 mt-0 d-inline-block text-left mx-auto mb-4" style="width: 100px;">
                </div>
                <div class="footer-explanation right-border" style="border-right: 1px solid lightgray; ">
                    <h5 class="text-center complement-roboto-bold">Thanks for visiting our site.</h5>
                    <p>
                        <strong>Disclaimer!</strong> This site should <strong>not</strong> be used to fulfil any
                        purchases with valid banking information. The Nile website lacks
                        robust security standards and industry compliance protocols, while relying only on rudimentary
                        protections.
                        This site was made to fulfill our term-project requirement for CSCI 4050 - Software Engineering
                        class at The University of Georgia.
                    </p>
                    <p class="legal" style="font-size: smaller"><em>All product information including ISBN,
                        publisher, and cover images
                        was taken from
                        <a id="amazonLink" href="https://www.amazon.com" target="_blank">Amazon.com</a>. We claim no
                        ownership for any
                        information. All rights go to their respective owner(s). Any information
                        on nilebookstore.com inconsistent to its representation on Amazon is purely unintentional,
                        originating from programming errors or faults in retrieving information by our team.
                    </em>
                    </p>
                    <p class="text-center">Our talented team includes:<br></p>
                    <div class="text-center"><strong>Manu Puduvalli, Samuel Yuen, Vrund Parikh, Lok Kwong,
                        and
                        Glen George</strong>
                    </div>
                    <br>
                    <div id="applicationStackGroup" class="text-center">
                        <p>Our application stack includes:</p>
                        <ul class="list-unstyled d-inline-block text-left">
                            <li><i class="fab fa-bootstrap mr-2 mb-3 fa-lg"></i> Bootstrap Framework</li>
                            <li><i class="fab fa-mdb mr-2 mb-3 fa-lg"></i>MDBootstrap Framework</li>
                            <li><i class="fab fa-python mr-2 mb-3 fa-lg"></i>Flask + Python</li>
                            <li><i class="fas fa-database mr-2 mb-3 fa-lg"></i>MySQL</li>
                            <li><i class="fab fa-microsoft mr-2 mb-3 fa-lg"></i>TypeScript</li>
                            <li><i class="fab fa-js mr-2 mb-3 fa-lg"></i>Vanilla JavaScript/JQuery</li>
                            <li><i class="fas fa-running mr-2 mb-3 fa-lg"></i>Agile + Scrum</li>
                        </ul>
                    </div>
                </div>
            </div>
            <hr class="clearfix w-100 d-md-none">
            <div class="col-md-6 text-center mx-auto left-border">
                <div class="text-center">
                    <h5 class="text-uppercase primary-md font-weight-normal"
                        style="letter-spacing: 3px;">Relevant Links</h5>
                    <hr class="blue darken-3 accent-2 mt-0 d-inline-block text-left mx-auto mb-5" style="width: 100px;">
                </div>
                <div class="row" style="font-size: large">
                    <div class="col-md-6">
                        <ul class="list-unstyled text-center rel-links">
                            <li class="mb-5">
                                <strong><a href="https://github.com/ssyuen/nile" target="_blank">Nile Source
                                    Repository<i class="fab fa-github fa-lg ml-2"></i></a></strong>
                            </li>

                            <li class="mb-5">
                                <a href="https://github.com/ssyuen/" target="_blank">Samuel Yuen <i
                                        class="fab fa-github fa-lg ml-2"></i></a>
                            </li>

                            <li class="mb-5">
                                <a href="https://github.com/manu-p-1/" target="_blank">Manu Puduvalli <i
                                        class="fab fa-github fa-lg ml-2"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-unstyled text-center rel-links">
                            <li class="mb-5">
                                <a href="https://github.com/Lok-Kwong" target="_blank">Lok Kwong <i
                                        class="fab fa-github fa-lg ml-2"></i></a>
                            </li>

                            <li class="mb-5">
                                <a href="https://github.com/glengeorge98" target="_blank"> Glen George <i
                                        class="fab fa-github fa-lg ml-2"></i></a>
                            </li>

                            <li class="z">
                                <a href="https://github.com/vrund99" target="_blank">Vrund Parikh <i
                                        class="fab fa-github fa-lg ml-2"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <hr class="clearfix w-100 d-md-none">
        </div>
    </div>
    <hr>
    <ul class="list-unstyled list-inline text-center py-2 easter-egg">
        {% if not session['logged_in'] %}

            <li class="list-inline-item reg-for-free">
                <h5 class="mb-1 complement">Register for free</h5>
            </li>
            <li class="list-inline-item reg-for-free">
                <a href="{{ url_for('common_bp.register') }}" class="href">
                    <button class="btn blue-gradient btn-rounded btn-sm primary waves-effect waves-light sign-btn"
                            id="footerSignUpBtn">Sign Up
                    </button>
                </a>
            </li>


        {% else %}
            <li class="list-inline-item reg-for-free">
                <h5 class="mb-1 complement">View my Profile</h5>
            </li>
            <li class="list-inline-item reg-for-free">
                {% if not session['admin'] %}
                    <a href="{{ url_for('user_bp.overview') }}" class="href">
                {% else %}
                    <a href="{{ url_for('admin_bp.overview') }}" class="href">
                {% endif %}
                <button class="btn blue-gradient btn-rounded btn-sm primary waves-effect waves-light sign-btn"
                        id="footerMyProfile">My Profile
                </button>
                </a>
            </li>
        {% endif %}

        <li class="list-inline-item">
            <form class="form-inline complement" action="{{ url_for('api_bp.query_books') }}">
                <div class="container-fluid search-group-parent">
                    <div class="input-group">
                        <input id="searchFooter" class="form-control main-search-sys" type="text" placeholder="Search"
                               aria-label="Search"
                               style="width: 500px;"
                               name="search_query">
                        <div class="input-group-append">
                            <button id="searchFooterBtn"
                                    class="btn blue-gradient m-0 px-4 py-2 z-depth-0 waves-effect mr-3 main-search-sys-btn"
                                    type="submit"><i class="fas fa-search" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </div>
            </form>
        </li>
    </ul>
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://www.nilebookstore.com/">nilebookstore.com</a>
    </div>
</footer>
<style>
    #amazonLink:hover {
        color: #028df5;
    }

    .fa-bootstrap:hover {
        color: #602C50 !important;
        background-color: white;
    }

    .fa-mdb:hover, .fa-python:hover {
        color: #028df5 !important;
    }

    .fa-database:hover {
        color: #cccccc !important;
    }

    .fa-microsoft:hover {
        color: #00A1F1 !important;
    }

    .fa-js:hover {
        color: #f7df1e !important;
    }

    .fa-running:hover {
        color: limegreen !important;
    }
</style>
<script> /* I minified this Javascript */
var ctr = 0, cp = 0;
$(function () {
    let c = $("footer");
    c.on("click", function () {
        ++ctr % 2 == 0 && cp + 3 === ctr ? (c.css("background", ""), cp = ctr) : ctr % 3 == 0 && 0 !== ctr && (c.css("background", "linear-gradient(40deg, #222e6f, #215c76)"), cp = ctr), 3 === ctr && $('<p class="text-center complement">You found the river gradient. Nice work!</p>').insertAfter(".easter-egg")
    })
});
</script>
</body>
</html>

templates/baseConfirm.html
{% extends "base.html" %}
{% block base_title %}
    {% block title %}{% endblock %} Confirmation
{% endblock %}

{% block base_head %}
    {{ super() }}
    {% block head %}
        <style>
            @media (max-width: 768px) {
                #acctContainer {
                    display: table-cell;
                }

                #acctContainer > .card {
                    width: auto !important;
                    padding: 2px !important;
                    height: 300px !important;
                    margin-top: 5em !important;
                }
            }

            #acctContainer {
                width: 750px;
                max-width: 75%;
                margin-top: 5em;
                margin-bottom: 5em;
                min-height: 100%;
            }
        </style>
    {% endblock head %}
    <script src="/static/common/js/baseConfirmation.js"></script>
{% endblock base_head %}

{% set titleable = false %}
{% block show_title %}
{% endblock %}

{% block main %}
    <div class="container" id="acctContainer">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title primary-md text-center">
                    {% block cardTitle %}
                    {% endblock %}
                </h5>
                <p class="card-text complement-light text-center my-3">
                    {% block content %}
                    {% endblock %}
                </p>
            </div>
            <div class="card-footer" id="optionalConfirmationFooter">
                {% block card_footer %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/common_links.html
{#<!-- These css and scripts are installed locally for performance -->#}


<link rel="preload" as="style" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<link rel="preload" as="style" href="/static/gfonts.css">
<link rel="preload" as="style" href="/static/gfontstwo.css">

<!-- For some reason, if you download this and use it, it doesn't like to render properly -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<link rel="stylesheet" href="/static/gfonts.css">
<link rel="stylesheet" href="/static/gfontstwo.css">


<link rel="preload" as="style" href="/static/mdb/css/bootstrap.min.css">
<link rel="preload" as="style" href="/static/mdb/css/mdb.min.css">

<link rel="stylesheet" href="/static/mdb/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/mdb/css/mdb.min.css">

<script src="/static/mdb/js/jquery.min.js"></script>
<script src="/static/mdb/js/popper.min.js"></script>
<script src="/static/mdb/js/bootstrap.min.js"></script>
<script src="/static/mdb/js/mdb.js"></script>


<link rel="preload" as="style" href="/static/common/css/common.css">
<link rel="preload" as="style" href="/static/common/css/nav.css">

<link rel="stylesheet" type="text/css" href="/static/common/css/common.css">
<link rel="stylesheet" type="text/css" href="/static/common/css/nav.css">

<link rel="preload" as="style" href="/static/mdb/css/jquery-ui.css">
<link rel="stylesheet" href="/static/mdb/css/jquery-ui.css">

<script src="/static/mdb/js/jquery-ui.js"></script>

<link rel="icon" href="/static/images/Misc/Icon/Nile River.png">

templates/nav.html
<script>
    $(document).ready(function () {
        if (window.location.pathname === '/') {
            $("#browse").addClass('active');
            $("#about").removeClass('active');
        } else if (window.location.href.includes('/about/')) {
            $("#about").addClass('active');
            $("#browse").removeClass('active');
        }
    })
</script>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <a class="navbar-brand primary waves-effect" href="/">
        <img src="/static/images/Misc/Nile Dark Bkgnd Rectangular.png" width="150"
             class="d-inline-block align top img-fluid"
             alt="Nile Logo" id="nileLogo">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
            aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item complement browseOrActive" id="browse">
                <a class="nav-link" href="{{ url_for('common_bp.landing_page') }}">Browse
                    <span class="sr-only">(current)</span>
                </a>
            </li>

            <li class="nav-item complement browseOrActive" id="about">
                <a class="nav-link" href="{{ url_for('common_bp.about') }}">About</a>
            </li>
        </ul>
        <ul class="navbar-nav navbar-center search-group">
            <li>
                <form class="form-inline complement" id="searchBar" action="{{ url_for('api_bp.query_books') }}">
                    <div class="container-fluid search-group-parent">

                        <div class="input-group main-search-sys shadow" style="width: 650px;">
                            <div class="input-group-prepend">
                                <label for="searchFilter" class="d-none"> </label>
                                <select class="dropdown custom-select our-color nav-search-group" name="searchFilter"
                                        style="width: 75px;" id="searchFilter">
                                    <option value="all" selected id="searchFilterAllOption">All</option>
                                    <option value="productType">Audiobook</option>
                                    <option value="productType">CD & E-Book</option>
                                    <option value="productType">Cookbook</option>
                                    <option value="productType">Graphic Novel</option>
                                    <option value="productType">Guide/Informative</option>
                                    <option value="productType">Novel</option>
                                    <option value="productType">Textbook</option>
                                </select>
                            </div>
                            <input id="mainSearch" class="form-control nav-search-group" type="text"
                                   placeholder="Search"
                                   aria-label="Search" name="search_query"
                                   aria-describedby="inputGroup-sizing-default">
                            <div class="input-group-append">
                                <button id="mainSearchSysBtn nav-search-group"
                                        class="btn btn-md blue-gradient m-0 px-4 py-2 z-depth-0 waves-effect main-search-sys-btn"
                                        type="submit"><i class="fas fa-search" aria-hidden="true"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto nav-flex-icons user-centric-btn">
            {% if not session['admin'] %}
                <li class="nav-item align-self-center mr-2">
                    <div class="widget-header mr-3 mt-1">
                        <a href="{{ url_for('common_bp.shopping_cart') }}"
                           class="icon icon-sm rounded-circle border text-center">
                            <i class="fa fa-shopping-cart text-center fa-1x"></i>
                        </a>
                        <span class="badge badge-pill badge-danger notify shadow"><span
                                id="cartTotal">{{ session['shopping_cart']|length }}</span></span>
                    </div>
                </li>
            {% endif %}

            {% if session['logged_in'] %}
                <li class="nav-item dropdown align-self-center">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                    <span class=" complement">Welcome, {{ session['firstName'] }} {% if session['admin'] %}<span
                            class="badge badge-primary ml-2">Admin</span>{% endif %}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-default"
                         aria-labelledby="navbarDropdownMenuLink-333">
                        {% if not session['admin'] %}
                            <a class="dropdown-item" href="{{ url_for('user_bp.overview') }}">My Profile</a>
                        {% else %}
                            <a class="dropdown-item" href="{{ url_for('admin_bp.overview') }}">My Admin Profile</a>
                        {% endif %}
                        <a class="dropdown-item" href="{{ url_for('common_bp.logout') }}">Sign Out</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{{ url_for('common_bp.login') }}" class="href">
                        <button class="btn blue-gradient btn-rounded btn-sm primary waves-effect waves-light sign-btn shadow"
                                id="signInBtn">Sign In
                        </button>
                    </a>
                </li>
            {% endif %}

            {% if not session['logged_in'] %}
                <li class="nav-item">
                    <a href="{{ url_for('common_bp.register') }}" class="href">
                        <button class="btn aqua-gradient btn-rounded btn-sm primary waves-effect waves-light sign-btn shadow"
                                id="signUpBtn">Sign Up
                        </button>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<script src="/static/common/js/base/nav.js"></script>